version: '3'

services:
  app_yafuz:
    container_name: app-yafuz
    build:
      context: .
      dockerfile: ./apps/app-yafuz/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  presale:
    container_name: presale
    build:
      context: .
      dockerfile: ./apps/presale/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
